# -*- coding: utf-8 -*-
"""projeto-aws.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRkFlYEkp0byN9mZf2DqjpTijR8YXS2R

# Projeto Integrador I - O Peso das Palavras
## Análise Exploratória e de Sentimentos em Marketplace (AWS)

**Disciplina:** Projeto Integrador I (PII1) · **Professor:** Prof. Dr. Felipe A. Camargo  
**Autores:** _Anderson Horácio, Felipe dos Santos, Giovanna Xavier, Guilherme Vilanova_

---

### Contexto e problema de negócio

Em marketplaces, a satisfação é expressa por **nota (1–5)** e **comentário textual**. Nem sempre ambos convergem, o que dificulta métricas automáticas de satisfação.

### Objetivo

Investigar a relação entre `review_score` e `review_comment_message`, identificando padrões, incoerências e comportamento dos clientes.

### Abordagem de sentimento (destaque)

A análise principal usa **Transformers (Hugging Face)**, modelo **BERT multilíngue** que processa português **sem tradução externa**. VADER e LeIA aparecem apenas como **referência comparativa** (modelos léxicos).

### Tabelas do projeto (9 CSV)

`pedidos`, `itens_pedidos`, `pagamentos`, `avaliacoes` (foco), `clientes`, `vendedores`, `produtos`, `geolocalizacao`, `tabela_auxiliar`.

### Fluxo do notebook

1. Carregamento → 2. Entendimento → 3. **Limpeza** → 4. **Features** → 5. **EDA** → 6. NLP → 7. Sentimentos → 8. Conclusões

### Execução no Colab

1. **Runtime → Change runtime type → T4 GPU**  
2. Envie a pasta `banco de dados` ao Drive ou faça upload no Colab  
3. Ajuste `PASTA_DADOS` na célula de carregamento  
4. **Runtime → Run all** (Transformers na base completa: ~1–3 h com GPU)

## 2. Instalação e bibliotecas
"""

# Instalação (Google Colab) — execute uma vez
import sys, subprocess

pacotes = [
    "pandas", "numpy", "matplotlib", "seaborn", "plotly",
    "nltk", "wordcloud", "vaderSentiment", "leia-br",
    "transformers", "torch", "accelerate", "tqdm",
    "scikit-learn", "scipy", "unidecode", "emoji",
]
for p in pacotes:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", p], check=False)

import nltk
for r in ["punkt", "punkt_tab", "stopwords", "rslp"]:
    try:
        nltk.download(r, quiet=True)
    except Exception:
        pass
print("Pacotes instalados.")

import warnings
import re
import os
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import cohen_kappa_score
from sklearn.feature_extraction.text import CountVectorizer
from IPython.display import display

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import RSLPStemmer
from wordcloud import WordCloud
import emoji
from unidecode import unidecode

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

CORES_NOTA = {1: "#d62728", 2: "#ff7f0e", 3: "#bcbd22", 4: "#2ca02c", 5: "#1f77b4"}
print("Bibliotecas carregadas:", datetime.now().strftime("%Y-%m-%d %H:%M"))

"""## 3. Carregamento dos dados

Ajuste `PASTA_DADOS` para o caminho da pasta que contém os 9 arquivos CSV.
"""

# Montar Drive (Colab) — ignore erro se rodar localmente
try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
except Exception:
    pass

# === AJUSTE AQUI ===
PASTA_DADOS = None
for caminho in [
    "/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/banco-de-dados",
    "/content/drive/MyDrive/banco-de-dados",
    "/content/banco-de-dados"
]:
    if os.path.isdir(caminho) and os.path.isfile(os.path.join(caminho, "avaliacoes.csv")):
        PASTA_DADOS = caminho
        break

if PASTA_DADOS is None:
    raise FileNotFoundError("Pasta 'banco de dados' não encontrada. Ajuste PASTA_DADOS.")

print("Pasta:", PASTA_DADOS)

def ler_csv(nome):
    path = os.path.join(PASTA_DADOS, nome)
    for enc in ("utf-8", "latin-1", "iso-8859-1"):
        try:
            return pd.read_csv(path, encoding=enc, low_memory=False)
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, low_memory=False)

pedidos = ler_csv("pedidos.csv")
itens = ler_csv("itens_pedidos.csv")
clientes = ler_csv("clientes.csv")
produtos = ler_csv("produtos.csv")
pagamentos = ler_csv("pagamentos.csv")
avaliacoes = ler_csv("avaliacoes.csv")
vendedores = ler_csv("vendedores.csv")
geo = ler_csv("geolocalizacao.csv")
aux = ler_csv("tabela_auxiliar.csv")

tabelas = {
    "pedidos": pedidos, "itens_pedidos": itens, "clientes": clientes,
    "produtos": produtos, "pagamentos": pagamentos, "avaliacoes": avaliacoes,
    "vendedores": vendedores, "geolocalizacao": geo, "tabela_auxiliar": aux,
}

for nome, df in tabelas.items():
    print(f"{nome:20s} → {df.shape[0]:>8,} linhas × {df.shape[1]} colunas")

# Visão geral rápida — todas as tabelas
for nome, df in tabelas.items():
    print("=" * 60)
    print(nome.upper(), df.shape)
    display(df.head(3))
    print("Nulos (%):\n", (df.isna().mean() * 100).round(2))
    display(df.describe(include="all").T.head(12))

"""## 4. Entendimento das tabelas

**Pergunta guia:** como os dados se conectam para explicar a jornada do cliente até a avaliação?

**Fluxo:** cliente → pedido → itens / pagamento → avaliação  
**Chave central:** `order_id`

| Tabela | Papel |
|--------|-------|
| avaliacoes | Nota + texto (foco do projeto) |
| pedidos | Datas de compra e entrega (prazo) |
| clientes | Estado/região do comprador |
| itens_pedidos | Itens por pedido |
"""

pedidos_ids = set(pedidos["order_id"])
print("Integridade — chaves órfãs:")
print("  Avaliações sem pedido:", (~avaliacoes["order_id"].isin(pedidos_ids)).sum())
print("  Itens sem pedido:", (~itens["order_id"].isin(pedidos_ids)).sum())
print("  Pagamentos sem pedido:", (~pagamentos["order_id"].isin(pedidos_ids)).sum())

"""## 5. Limpeza e tratamento dos dados

Todas as análises seguintes usam **dados já tratados**. Nenhuma amostragem — apenas duplicatas e padronização.

**Texto consolidado:** quando o comentário estiver vazio, usamos o **título** como fallback (`texto_final_avaliacao`), conforme orientação do professor.
"""

# Duplicatas
n_dup = avaliacoes.duplicated(subset=["review_id"]).sum()
avaliacoes = avaliacoes.drop_duplicates(subset=["review_id"], keep="first")
print(f"Duplicatas removidas em avaliacoes: {n_dup}")

# Datas — todas as tabelas relevantes
for col in ["review_creation_date", "review_answer_timestamp"]:
    avaliacoes[col] = pd.to_datetime(avaliacoes[col], errors="coerce")
for col in ["order_purchase_timestamp", "order_delivered_customer_date", "order_estimated_delivery_date"]:
    if col in pedidos.columns:
        pedidos[col] = pd.to_datetime(pedidos[col], errors="coerce")

# Texto bruto
avaliacoes["review_comment_message"] = avaliacoes["review_comment_message"].fillna("").str.strip()
avaliacoes["review_comment_title"] = avaliacoes["review_comment_title"].fillna("").str.strip()

# Coluna consolidada: comentário prioritário; título como fallback
avaliacoes["texto_final_avaliacao"] = np.where(
    avaliacoes["review_comment_message"].str.len() > 0,
    avaliacoes["review_comment_message"],
    avaliacoes["review_comment_title"],
)
avaliacoes["usou_titulo_fallback"] = (
    (avaliacoes["review_comment_message"].str.len() == 0)
    & (avaliacoes["review_comment_title"].str.len() > 0)
)

print(f"Avaliacoes com comentario: {(avaliacoes['review_comment_message'].str.len() > 0).sum():,}")
print(f"Avaliacoes com titulo fallback: {avaliacoes['usou_titulo_fallback'].sum():,}")
print(f"Avaliacoes com texto_final_avaliacao: {(avaliacoes['texto_final_avaliacao'].str.len() > 0).sum():,}")

# Padronização de cidades
clientes["customer_state"] = clientes["customer_state"].astype(str).str.upper().str.strip()
if "customer_city" in clientes.columns:
    clientes["customer_city"] = clientes["customer_city"].astype(str).str.lower().str.strip()

print("Limpeza concluida.")

"""## 6. Variáveis derivadas (feature engineering)

Criamos variáveis de **prazo**, **atraso** e **região** para investigar o impacto da entrega na satisfação.
"""

# Prazo e atraso (pedidos entregues)
pedidos["dias_entrega"] = (
    pedidos["order_delivered_customer_date"] - pedidos["order_purchase_timestamp"]
).dt.days
pedidos["dias_atraso"] = (
    pedidos["order_delivered_customer_date"] - pedidos["order_estimated_delivery_date"]
).dt.days
pedidos["atrasou"] = (pedidos["dias_atraso"] > 0).astype(int)
pedidos["no_prazo"] = (pedidos["dias_atraso"] <= 0).astype(int)

# Faixas de atraso
pedidos["faixa_atraso"] = pd.cut(
    pedidos["dias_atraso"].fillna(0),
    bins=[-999, 0, 3, 7, 999],
    labels=["no_prazo", "atraso_leve", "atraso_medio", "atraso_grave"],
)

# Trimestre da compra (análise temporal de atrasos)
pedidos["trimestre"] = pedidos["order_purchase_timestamp"].dt.to_period("Q").astype(str)

# Agregação por pedido
agg_itens = itens.groupby("order_id").agg(
    qtd_itens=("order_item_id", "count"),
    valor_total=("price", "sum"),
).reset_index()

# Base analítica: 1 linha por avaliação (dados limpos)
base = avaliacoes.merge(pedidos, on="order_id", how="left")
base = base.merge(agg_itens, on="order_id", how="left")
base = base.merge(clientes[["customer_id", "customer_state"]], on="customer_id", how="left")

base["tam_texto"] = base["texto_final_avaliacao"].str.len()

print("Base analitica:", base.shape)
display(base[[
    "review_score", "texto_final_avaliacao", "usou_titulo_fallback",
    "dias_atraso", "atrasou", "faixa_atraso", "customer_state"
]].head())

"""## 7. Análise exploratória (dados tratados)

**Hipóteses investigadas:**
1. Atraso na entrega reduz a nota?
2. Pedidos atrasados concentram avaliações piores?
3. Estados com mais atrasos também têm pior satisfação?
4. Em quais trimestres houve mais atrasos?
"""

# 7.1 Comportamento das avaliações
print("Distribuicao da nota:")
display(base["review_score"].value_counts().sort_index())

fig, ax = plt.subplots(figsize=(8, 4))
base["review_score"].value_counts().sort_index().plot(
    kind="bar",
    color=[CORES_NOTA.get(i, "gray") for i in sorted(base["review_score"].dropna().unique())],
    ax=ax,
)
ax.set_title("Distribuicao das notas (base tratada)"); ax.set_xlabel("Nota"); ax.set_ylabel("N")
plt.tight_layout(); plt.show()

n_fallback = base["usou_titulo_fallback"].sum()
n_texto = (base["texto_final_avaliacao"].str.len() > 0).sum()
print(f"Texto disponivel (comentario ou titulo): {n_texto:,} ({n_texto/len(base)*100:.1f}%)")
print(f"Usou titulo como fallback: {n_fallback:,}")
print("Interpretacao: notas altas predominam; fallback de titulo amplia cobertura para NLP/sentimento.")

# 7.2 ENTREGA E ATRASO x NOTA
entregues = base[base["order_delivered_customer_date"].notna()].copy()
print(f"Pedidos com data de entrega: {len(entregues):,}")

# Atraso x nota
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=entregues, x="atrasou", y="review_score", ax=axes[0])
axes[0].set_xticklabels(["No prazo", "Atrasou"])
axes[0].set_title("Será que atraso reduz a nota?")

nota_faixa = entregues.groupby("faixa_atraso", observed=True)["review_score"].agg(["mean", "count"])
nota_faixa["mean"].plot(kind="bar", ax=axes[1], color="steelblue", edgecolor="black")
axes[1].set_title("Nota media por faixa de atraso"); axes[1].set_ylabel("Nota media")
axes[1].tick_params(axis="x", rotation=20)
plt.tight_layout(); plt.show()

corr_atraso_nota = entregues["dias_atraso"].corr(entregues["review_score"])
pct_atraso = entregues["atrasou"].mean() * 100
nota_atraso = entregues.groupby("atrasou")["review_score"].mean()
print(f"Correlacao dias_atraso x nota: {corr_atraso_nota:.4f}")
print(f"% pedidos atrasados: {pct_atraso:.1f}%")
print("Nota media — no prazo:", round(nota_atraso.get(0, np.nan), 3),
      "| atrasados:", round(nota_atraso.get(1, np.nan), 3))
print("Interpretacao: atraso associa-se a notas menores; impacto mensuravel na satisfacao.")

# 7.3 Atrasos por TRIMESTRE
ped_ent = pedidos[pedidos["order_delivered_customer_date"].notna()].copy()
tri = ped_ent.groupby("trimestre").agg(
    total_pedidos=("order_id", "count"),
    pedidos_atrasados=("atrasou", "sum"),
    pct_atraso=("atrasou", "mean"),
    dias_atraso_medio=("dias_atraso", "mean"),
).reset_index()
tri["pct_atraso"] = (tri["pct_atraso"] * 100).round(2)
display(tri.sort_values("trimestre"))

fig, ax1 = plt.subplots(figsize=(12, 5))
x = range(len(tri))
ax1.bar(x, tri["pedidos_atrasados"], color="indianred", label="Qtd. atrasados")
ax1.set_xticks(x); ax1.set_xticklabels(tri["trimestre"], rotation=45)
ax1.set_ylabel("Pedidos atrasados")
ax2 = ax1.twinx()
ax2.plot(x, tri["pct_atraso"], color="navy", marker="o", linewidth=2, label="% atraso")
ax2.set_ylabel("% atraso")
plt.title("Periodos criticos: volume e percentual de atraso por trimestre")
plt.tight_layout(); plt.show()

pico = tri.loc[tri["pct_atraso"].idxmax(), "trimestre"]
print(f"Trimestre com maior % de atraso: {pico}")
print("Interpretacao: identificar janelas logisticas criticas para narrativa da conclusao.")

# 7.4 ANALISE REGIONAL — pedidos, atraso e satisfacao
ped_est = pedidos.merge(clientes[["customer_id", "customer_state"]], on="customer_id", how="left")
ped_est = ped_est[ped_est["customer_state"].notna() & (ped_est["customer_state"] != "nan")]

regiao_pedidos = ped_est.groupby("customer_state").agg(
    qtd_pedidos=("order_id", "count"),
    pct_atraso=("atrasou", "mean"),
    dias_atraso_medio=("dias_atraso", "mean"),
).sort_values("qtd_pedidos", ascending=False)

regiao_aval = base.groupby("customer_state").agg(
    nota_media=("review_score", "mean"),
    qtd_avaliacoes=("review_id", "count"),
).sort_values("qtd_avaliacoes", ascending=False)

regional = regiao_pedidos.join(regiao_aval, how="outer")
regional["pct_atraso"] = (regional["pct_atraso"] * 100).round(2)
regional = regional.sort_values("qtd_pedidos", ascending=False)

print("=== Estados: volume, atraso e satisfacao ===")
display(regional.head(15))

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
top = regional.head(12)
top["qtd_pedidos"].plot(kind="barh", ax=axes[0], color="teal")
axes[0].set_title("Estados com mais pedidos")
top["nota_media"].sort_values().plot(kind="barh", ax=axes[1], color="orange")
axes[1].set_title("Nota media por estado (top 12 volume)")
plt.tight_layout(); plt.show()

pior_nota = regional["nota_media"].idxmin()
maior_atraso = regional["pct_atraso"].idxmax()
print(f"Estado com menor nota media: {pior_nota}")
print(f"Estado com maior % atraso: {maior_atraso}")
print("Interpretacao: comparar volume, prazo e satisfacao fortalece leitura regional.")

"""## 8. Análise de texto (pré-processamento)

Usamos `texto_final_avaliacao` (comentário ou título fallback). Corpus **integral** — 100% dos textos disponíveis.

**Pergunta:** quais termos aparecem nas avaliações negativas vs. positivas?
"""

stop_pt = set(stopwords.words("portuguese"))

com_texto = avaliacoes[avaliacoes["texto_final_avaliacao"].str.len() > 0].copy()
print("Registros com texto_final_avaliacao:", len(com_texto))
print("Desses, usaram titulo fallback:", com_texto["usou_titulo_fallback"].sum())

tokens_lista = []
for texto in com_texto["texto_final_avaliacao"]:
    t = str(texto).lower()
    t = re.sub(r"http\S+", " ", t)
    t = re.sub(r"[^a-záàâãéèêíïóôõöúçñ\s]", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    tok = [w for w in word_tokenize(t, language="portuguese") if w not in stop_pt and len(w) > 2]
    tokens_lista.append(" ".join(tok))

com_texto = com_texto.assign(tokens=tokens_lista)
corpus = " ".join(com_texto["tokens"])

wc = WordCloud(width=1200, height=500, max_words=150, background_color="white").generate(corpus)
plt.figure(figsize=(14, 6)); plt.imshow(wc); plt.axis("off")
plt.title(f"Nuvem de palavras — {len(com_texto):,} textos"); plt.show()

# Bigramas (base completa)
vec = CountVectorizer(ngram_range=(2, 2), max_features=25, min_df=10)
X = vec.fit_transform(com_texto["tokens"])
bigramas = pd.Series(X.sum(axis=0).A1, index=vec.get_feature_names_out()).sort_values(ascending=False)
print("Top bigramas:"); display(bigramas.head(20))

"""## 9. Análise de sentimentos

### Por que Transformers é a abordagem principal?

| | Modelo léxico (VADER/LeIA) | Transformers (BERT) |
|---|---------------------------|---------------------|
| Mecanismo | Dicionário + regras | Rede neural + atenção |
| Contexto | Palavra a palavra | Frase inteira (bidirecional) |
| Português | LeIA adapta léxico; VADER é inglês | Modelo multilíngue processa PT **nativamente** |
| Ambiguidade | Fraca | Melhor (“produto bom, entrega ruim”) |

**BERT** gera embeddings contextuais — cada palavra depende das vizinhas. O professor indica Transformers como método **mais robusto e moderno**.

**Modelo:** `nlptown/bert-base-multilingual-uncased-sentiment` (1–5 estrelas, sem `deep_translator`).

**Limitações:** custo computacional; ironia extrema; registros sem texto e sem título recebem score neutro.

**Entrada do modelo:** coluna `texto_final_avaliacao` (comentário prioritário; título quando comentário vazio).
"""

# Classificação em 3 classes (Etapa 2 do professor)
def classe_sentimento(score):
    if pd.isna(score):
        return "neutro"
    if score <= -0.1:
        return "negativo"
    if score < 0.1:
        return "neutro"
    return "positivo"

def estrelas_para_compound(label, confianca):
    mapa = {"1 star": -1.0, "2 stars": -0.5, "3 stars": 0.0, "4 stars": 0.5, "5 stars": 1.0}
    return mapa.get(label, 0.0) * float(confianca)

def estrelas_para_numero(label):
    try:
        return int(str(label).split()[0])
    except Exception:
        return np.nan

# --- TRANSFORMERS: inferência em 100% dos comentários com texto ---
from transformers import pipeline
import torch
from tqdm.auto import tqdm

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("AVISO: ative GPU no Colab (Runtime > Change runtime type > T4 GPU)")

NOME_MODELO = "nlptown/bert-base-multilingual-uncased-sentiment"
DEVICE = 0 if torch.cuda.is_available() else -1
LOTE = 64 if torch.cuda.is_available() else 16

classificador = pipeline(
    "sentiment-analysis",
    model=NOME_MODELO,
    tokenizer=NOME_MODELO,
    device=DEVICE,
    truncation=True,
    max_length=512,
)

sent = avaliacoes[[
    "review_id", "order_id", "review_score",
    "texto_final_avaliacao", "usou_titulo_fallback"
]].copy()
sent["tf_compound"] = 0.0
sent["tf_estrelas"] = np.nan
sent["tf_label_raw"] = ""
sent["tf_confianca"] = np.nan

mask = sent["texto_final_avaliacao"].str.strip().astype(bool)
idx = sent.index[mask]
textos = sent.loc[idx, "texto_final_avaliacao"].tolist()
print(f"Inferencia BERT em {len(textos):,} textos (comentario + titulo fallback)...")
print(f"  Destes, {sent.loc[idx, 'usou_titulo_fallback'].sum():,} vieram do titulo")

saida = []
for i in tqdm(range(0, len(textos), LOTE), desc="BERT"):
    lote = textos[i : i + LOTE]
    try:
        saida.extend(classificador(lote))
    except Exception as e:
        print("Erro lote", i, e)
        saida.extend([{"label": "3 stars", "score": 0.5}] * len(lote))

for i, row_idx in enumerate(idx):
    r = saida[i]
    sent.at[row_idx, "tf_label_raw"] = r["label"]
    sent.at[row_idx, "tf_confianca"] = r["score"]
    sent.at[row_idx, "tf_compound"] = estrelas_para_compound(r["label"], r["score"])
    sent.at[row_idx, "tf_estrelas"] = estrelas_para_numero(r["label"])

sent["tf_classe"] = sent["tf_compound"].apply(classe_sentimento)
print("Transformers concluído.")
display(sent.loc[mask, ["review_score", "texto_final_avaliacao", "usou_titulo_fallback", "tf_estrelas", "tf_compound", "tf_classe"]].head(8))

"""**Interpretação:** `tf_estrelas` compara com `review_score`. O fallback de título aumenta cobertura sem distorcer quem já comentou.

### 9.1 Modelos léxicos (somente comparação pedagógica)

VADER e LeIA rodam na **base completa** para contrastar com o BERT. Não usamos tradução externa.
"""

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
try:
    from LeIA import SentimentIntensityAnalyzer as LeIAAnalyzer
except ImportError:
    from leia import SentimentIntensityAnalyzer as LeIAAnalyzer

vader = SentimentIntensityAnalyzer()
leia = LeIAAnalyzer()

def compound_lex(analisador, texto):
    if not str(texto).strip():
        return 0.0
    return analisador.polarity_scores(str(texto))["compound"]

print("VADER — base completa...")
sent["vader_compound"] = sent["texto_final_avaliacao"].apply(lambda t: compound_lex(vader, t))
sent["vader_classe"] = sent["vader_compound"].apply(classe_sentimento)

print("LeIA — base completa...")
sent["leia_compound"] = sent["texto_final_avaliacao"].apply(lambda t: compound_lex(leia, t))
sent["leia_classe"] = sent["leia_compound"].apply(classe_sentimento)

print("Modelos léxicos concluídos.")

"""## 10. Comparação de modelos e entrega × sentimento

**Perguntas:**
- Qual modelo alinha melhor com a nota?
- Pedidos atrasados têm mais comentários negativos (Transformers)?
"""

com = sent[sent["texto_final_avaliacao"].str.strip().astype(bool)].copy()
com = com.merge(
    base[["order_id", "atrasou", "faixa_atraso", "dias_atraso", "customer_state"]],
    on="order_id", how="left",
)
print("N com textos para analise:", len(com))

linhas = []
for nome, col_est, col_comp in [
    ("Transformers", "tf_estrelas", "tf_compound"),
    ("LeIA", None, "leia_compound"),
    ("VADER", None, "vader_compound"),
]:
    sub = com[[col_comp, "review_score"]].dropna()
    pr = pearsonr(sub[col_comp], sub["review_score"])[0]
    sp = spearmanr(sub[col_comp], sub["review_score"])[0]
    mae = np.nan
    if col_est:
        s2 = com[[col_est, "review_score"]].dropna()
        mae = (s2[col_est] - s2["review_score"]).abs().mean()
    linhas.append({"modelo": nome, "N": len(sub), "pearson": pr, "spearman": sp, "MAE_estrelas": mae})

display(pd.DataFrame(linhas).round(4))
print("Interpretação: maior correlação e menor MAE em estrelas indicam melhor alinhamento com a nota do cliente.")

# Gráficos de dispersão — densidade (100%, sem amostragem)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for ax, nome, col in zip(axes,
    ["Transformers", "LeIA", "VADER"],
    ["tf_compound", "leia_compound", "vader_compound"]):
    sub = com[[col, "review_score"]].dropna()
    ax.hexbin(sub[col], sub["review_score"], gridsize=45, cmap="YlOrRd", mincnt=1)
    ax.set_xlabel(col); ax.set_ylabel("review_score")
    ax.set_title(f"{nome} (N={len(sub):,})")
plt.suptitle("Coerência nota × sentimento — base integral", y=1.02)
plt.tight_layout(); plt.show()

# Concordância Transformers × LeIA
tab = pd.crosstab(com["tf_classe"], com["leia_classe"])
sns.heatmap(tab, annot=True, fmt="d", cmap="Blues")
plt.title("Classes: Transformers × LeIA"); plt.show()
print("Kappa:", round(cohen_kappa_score(com["tf_classe"], com["leia_classe"]), 4))

# Atraso x sentimento (Transformers)
print("=== Atraso x sentimento ===")
sent_atraso = com.groupby("atrasou").agg(
    tf_compound_medio=("tf_compound", "mean"),
    pct_negativo=("tf_classe", lambda s: (s == "negativo").mean() * 100),
    n=("review_id", "count"),
)
display(sent_atraso)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.boxplot(data=com, x="atrasou", y="tf_compound", ax=axes[0])
axes[0].set_xticklabels(["No prazo", "Atrasou"])
axes[0].set_title("Sentimento (compound) x atraso")

ct_atraso = pd.crosstab(com["atrasou"], com["tf_classe"], normalize="index") * 100
sns.heatmap(ct_atraso, annot=True, fmt=".1f", cmap="RdYlGn_r", ax=axes[1])
axes[1].set_title("% classe de sentimento por atraso")
plt.tight_layout(); plt.show()

corr_atraso_sent = com["dias_atraso"].corr(com["tf_compound"])
print(f"Correlacao dias_atraso x tf_compound: {corr_atraso_sent:.4f}")
print("Interpretacao: atraso tende a coincidir com sentimento mais negativo — evidencia para conclusao.")

"""## 11. Incoerências (nota × sentimento)

**Pergunta:** existe comentário positivo com nota baixa (ou o inverso)?  
Detectamos com **Transformers** sobre `texto_final_avaliacao`.
"""

def faixa_nota(n):
    if n <= 2: return "baixa"
    if n == 3: return "media"
    return "alta"

com["faixa_nota"] = com["review_score"].apply(faixa_nota)
com["faixa_sent"] = com["tf_compound"].apply(
    lambda x: "baixa" if x <= -0.1 else ("media" if x < 0.1 else "alta")
)
com["incoerente"] = com["faixa_nota"] != com["faixa_sent"]

print(f"Taxa de incoerência (Transformers): {com['incoerente'].mean()*100:.2f}%")
print(f"Divergência >= 2 estrelas (predito vs real): {(com['tf_estrelas'] - com['review_score']).abs().ge(2).mean()*100:.2f}%")

print("\n--- Exemplos: texto positivo, nota baixa ---")
display(com[(com["review_score"] <= 2) & (com["tf_compound"] >= 0.3)][
    ["review_score", "tf_estrelas", "tf_compound", "texto_final_avaliacao", "usou_titulo_fallback"]].head(5))

print("\n--- Exemplos: texto negativo, nota alta ---")
display(com[(com["review_score"] >= 4) & (com["tf_compound"] <= -0.3)][
    ["review_score", "tf_estrelas", "tf_compound", "texto_final_avaliacao", "usou_titulo_fallback"]].head(5))

print("Possíveis causas: sarcasmo, foco em entrega vs produto, nota automática/hábito, limite do modelo.")

"""## 12. Síntese visual — coerência nota × sentimento"""

ct = pd.crosstab(com["review_score"], com["tf_classe"], normalize="index")
plt.figure(figsize=(8, 5))
sns.heatmap(ct, annot=True, fmt=".1%", cmap="YlOrRd")
plt.title("Classe Transformers dentro de cada nota"); plt.ylabel("Nota"); plt.show()

ordem_cls = [c for c in ["negativo", "neutro", "positivo"] if c in com["tf_classe"].unique()]
plt.figure(figsize=(9, 5))
sns.violinplot(data=com, x="tf_classe", y="review_score", order=ordem_cls)
plt.title(f"Nota por classe Transformers (N={len(com):,})"); plt.show()

# Exportar base final
export = base.merge(
    sent[["order_id", "tf_compound", "tf_estrelas", "tf_classe", "leia_compound", "vader_compound"]],
    on="order_id", how="left",
)
export.to_csv("resultado_analise_completa.csv", index=False)
print("Exportado: resultado_analise_completa.csv")

"""## 13. Insights de negócio (evidências)"""

termos_nota1 = com_texto[com_texto["review_score"] == 1]["tokens"].str.split().explode().value_counts().head(8)
taxa_inc = com["incoerente"].mean() * 100

print("=== INSIGHTS PARA A CONCLUSAO ===")
print(f"1. Correlacao atraso x nota: {corr_atraso_nota:.4f}")
print(f"2. Correlacao atraso x sentimento (BERT): {corr_atraso_sent:.4f}")
print(f"3. Nota media no prazo vs atrasado: {nota_atraso.get(0, np.nan):.2f} vs {nota_atraso.get(1, np.nan):.2f}")
print(f"4. Taxa de incoerencia nota x texto: {taxa_inc:.2f}%")
print(f"5. Textos via titulo fallback: {base['usou_titulo_fallback'].sum():,}")
print(f"6. Termos em nota 1: {', '.join(termos_nota1.index.astype(str))}")
print(f"7. Trimestre critico de atraso: {pico}")
print(f"8. Estado maior % atraso: {maior_atraso} | menor nota: {pior_nota}")

"""## 14. Conclusão

### Resposta ao problema de negócio

O projeto investigou a relação entre **nota** e **texto** nas avaliações de um marketplace. Com dados tratados e análise em **100% da base**, concluímos:

1. **Prazo de entrega importa:** a correlação entre `dias_atraso` e `review_score` e a queda da nota média em pedidos atrasados mostram que **logística é driver de insatisfação** — alinhado à ênfase do professor.

2. **Sentimento confirma o padrão:** pedidos atrasados apresentam `tf_compound` mais baixo e maior proporção de classe negativa (Transformers), reforçando que atraso não afeta só a nota, mas também o **tom do comentário**.

3. **Períodos críticos:** o gráfico trimestral de atrasos revela janelas com pior desempenho logístico — útil para narrar causas sazonais ou operacionais.

4. **Dimensão regional:** estados com mais pedidos nem sempre têm melhor nota; combinar volume, `% atraso` e `nota_media` evidencia heterogeneidade na experiência do cliente.

5. **Nota ≠ texto sempre:** a taxa de incoerência (nota vs. sentimento BERT) mostra que estrelas e comentários são **complementares**. O fallback de **título** quando o comentário está vazio melhorou a cobertura textual sem distorcer quem já escreveu.

6. **Modelo de sentimento:** **Transformers (BERT multilíngue)** superou VADER/LeIA em alinhamento com a nota, por capturar **contexto** em português — sem tradução externa.

### Evidências-chave (preencher com valores do notebook)

| Evidência | Indicador |
|-----------|-----------|
| Impacto do atraso na nota | Correlação + nota média atrasado vs. no prazo |
| Impacto do atraso no sentimento | `tf_compound` e % negativo por `atrasou` |
| Período crítico | Trimestre com maior `% atraso` |
| Região sensível | Estado com maior atraso / menor nota |
| Incoerência | % nota × sentimento divergentes |

### Limitações

- Inferência BERT exige GPU e tempo; ironia e gírias ainda falham; viés de notas 5; títulos curtos podem ser ambíguos.

### Recomendações

- Monitorar trimestres e estados com pior `% atraso`; priorizar SAC em avaliações com sentimento negativo e nota alta (incoerência); usar Transformers como motor de alerta textual.

---

**Referências:** PII1 — Prof. Felipe A. Camargo; Hutto & Gilbert (2014); Hugging Face; `nlptown/bert-base-multilingual-uncased-sentiment`.
"""